--
-- PostgreSQL database dump
--

\restrict cuQanobPXERIwTwzrNhEhB7vhlyViNp6TJ5W0SZU9U89DRaDNanuOM68RkC1Pig

-- Dumped from database version 14.22
-- Dumped by pg_dump version 14.22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Alunos; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Alunos" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "NumeroChamada" integer NOT NULL,
    "DataNascimento" date NOT NULL,
    "Ativo" boolean NOT NULL,
    "TurmaId" integer NOT NULL,
    "AnoLetivoId" integer NOT NULL,
    "UserId" integer NOT NULL
);


ALTER TABLE public."Alunos" OWNER TO admin_escola_db;

--
-- Name: Alunos_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Alunos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Alunos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: AnosLetivos; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."AnosLetivos" (
    "Id" integer NOT NULL,
    "Ano" integer NOT NULL,
    "Ativo" boolean NOT NULL
);


ALTER TABLE public."AnosLetivos" OWNER TO admin_escola_db;

--
-- Name: AnosLetivos_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."AnosLetivos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AnosLetivos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DesenvolvimentosMaternal; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."DesenvolvimentosMaternal" (
    "Id" integer NOT NULL,
    "Bimestre" integer NOT NULL,
    "Descricao" text NOT NULL,
    "AlunoId" integer NOT NULL,
    "TurmaId" integer NOT NULL,
    "AnoLetivoId" integer NOT NULL
);


ALTER TABLE public."DesenvolvimentosMaternal" OWNER TO admin_escola_db;

--
-- Name: DesenvolvimentosMaternal_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."DesenvolvimentosMaternal" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DesenvolvimentosMaternal_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DiasLetivos; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."DiasLetivos" (
    "Id" integer NOT NULL,
    "Data" date NOT NULL,
    "AnoLetivoId" integer NOT NULL,
    "Segmento" text DEFAULT 'Fundamental'::text NOT NULL
);


ALTER TABLE public."DiasLetivos" OWNER TO admin_escola_db;

--
-- Name: DiasLetivos_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."DiasLetivos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."DiasLetivos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Disciplinas; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Disciplinas" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Ativo" boolean NOT NULL,
    "Segmento" text DEFAULT ''::text NOT NULL
);


ALTER TABLE public."Disciplinas" OWNER TO admin_escola_db;

--
-- Name: Disciplinas_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Disciplinas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Disciplinas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: FrequenciaAlunos; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."FrequenciaAlunos" (
    "Id" integer NOT NULL,
    "Presente" boolean NOT NULL,
    "FrequenciaId" integer NOT NULL,
    "AlunoId" integer NOT NULL,
    "Observacao" text
);


ALTER TABLE public."FrequenciaAlunos" OWNER TO admin_escola_db;

--
-- Name: FrequenciaAlunos_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."FrequenciaAlunos" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."FrequenciaAlunos_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Frequencias; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Frequencias" (
    "Id" integer NOT NULL,
    "Data" date NOT NULL,
    "TurmaId" integer NOT NULL,
    "AnoLetivoId" integer NOT NULL
);


ALTER TABLE public."Frequencias" OWNER TO admin_escola_db;

--
-- Name: Frequencias_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Frequencias" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Frequencias_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Notas; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Notas" (
    "Id" integer NOT NULL,
    "Unidade" integer NOT NULL,
    "Valor" numeric NOT NULL,
    "AlunoId" integer NOT NULL,
    "DisciplinaId" integer NOT NULL,
    "TurmaId" integer NOT NULL,
    "AnoLetivoId" integer NOT NULL
);


ALTER TABLE public."Notas" OWNER TO admin_escola_db;

--
-- Name: Notas_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Notas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Notas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: RelatosAula; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."RelatosAula" (
    "Id" integer NOT NULL,
    "Descricao" text NOT NULL,
    "DiaLetivoId" integer NOT NULL,
    "TurmaId" integer NOT NULL,
    "ProfessorId" integer NOT NULL
);


ALTER TABLE public."RelatosAula" OWNER TO admin_escola_db;

--
-- Name: RelatosAula_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."RelatosAula" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."RelatosAula_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: TurmaDisciplinaProfessores; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."TurmaDisciplinaProfessores" (
    "Id" integer NOT NULL,
    "TurmaId" integer NOT NULL,
    "DisciplinaId" integer NOT NULL,
    "ProfessorId" integer NOT NULL,
    "AnoLetivoId" integer NOT NULL
);


ALTER TABLE public."TurmaDisciplinaProfessores" OWNER TO admin_escola_db;

--
-- Name: TurmaDisciplinaProfessores_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."TurmaDisciplinaProfessores" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TurmaDisciplinaProfessores_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Turmas; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Turmas" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Segmento" text NOT NULL,
    "Ativo" boolean NOT NULL,
    "AnoLetivoId" integer NOT NULL
);


ALTER TABLE public."Turmas" OWNER TO admin_escola_db;

--
-- Name: Turmas_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Turmas" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Turmas_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Nome" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "Ativo" boolean NOT NULL
);


ALTER TABLE public."Users" OWNER TO admin_escola_db;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: admin_escola_db
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: admin_escola_db
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO admin_escola_db;

--
-- Data for Name: Alunos; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Alunos" ("Id", "Nome", "NumeroChamada", "DataNascimento", "Ativo", "TurmaId", "AnoLetivoId", "UserId") FROM stdin;
2	Pedro Lima	1	2017-06-20	t	2	1	4
4	Luquinhas	1	2021-01-07	t	4	2	6
12	Maria	1	2022-05-01	f	5	1	3
14	Maria	1	2022-03-02	f	5	1	3
15	teste	1	2024-12-11	f	3	1	3
16	Maria Souza	1	2023-05-02	t	6	5	3
17	Maria	1	2023-05-02	t	7	6	3
\.


--
-- Data for Name: AnosLetivos; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."AnosLetivos" ("Id", "Ano", "Ativo") FROM stdin;
1	2026	t
2	2025	f
3	2025	f
4	2025	t
5	2027	t
6	2028	t
\.


--
-- Data for Name: DesenvolvimentosMaternal; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."DesenvolvimentosMaternal" ("Id", "Bimestre", "Descricao", "AlunoId", "TurmaId", "AnoLetivoId") FROM stdin;
7	3	Maria demonstrou um bom desenvolvimento em seu comportamento.	16	6	5
9	1	Maria demonstrou um bom desenvolvimento para leitura.	16	6	5
8	4	Maria demonstrou um bom desenvolvimento em seus relacionamentos.	16	6	5
10	2	Maria demonstrou um bom desenvolvimento para escrita.	16	6	5
11	1	Maria demonstrou um bom desenvolvimento em seu comportamento.	17	7	6
13	3	Maria demonstrou um bom desenvolvimento em seu comportamento em sala.	17	7	6
12	4	Maria demonstrou um bom desenvolvimento em seu comportamento em sala.	17	7	6
14	2	Maria demonstrou um bom desenvolvimento em seus relacionamentos.	17	7	6
\.


--
-- Data for Name: DiasLetivos; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."DiasLetivos" ("Id", "Data", "AnoLetivoId", "Segmento") FROM stdin;
1	2028-01-03	6	Fundamental
2	2028-01-04	6	Fundamental
3	2028-01-05	6	Fundamental
4	2028-01-06	6	Fundamental
5	2028-01-07	6	Fundamental
6	2028-01-10	6	Fundamental
11	2026-03-02	1	Fundamental
12	2026-03-03	1	Fundamental
13	2026-03-10	1	Maternal
14	2026-01-20	1	Fundamental
\.


--
-- Data for Name: Disciplinas; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Disciplinas" ("Id", "Nome", "Ativo", "Segmento") FROM stdin;
3	Ciências	t	Fundamental
5	Geografia	t	Fundamental
4	História	t	Fundamental
1	Matemática	t	Fundamental
2	Português	t	Fundamental
6	Desenvolvimento infantil	t	Maternal
\.


--
-- Data for Name: FrequenciaAlunos; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."FrequenciaAlunos" ("Id", "Presente", "FrequenciaId", "AlunoId", "Observacao") FROM stdin;
1	t	1	2	\N
3	t	3	2	\N
2	t	2	2	\N
4	f	4	2	\N
5	t	5	16	\N
6	f	6	16	\N
7	f	7	17	\N
8	t	8	17	\N
9	t	9	17	\N
\.


--
-- Data for Name: Frequencias; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Frequencias" ("Id", "Data", "TurmaId", "AnoLetivoId") FROM stdin;
1	2026-04-27	2	1
3	2026-04-27	3	1
2	2026-04-28	2	1
4	2026-04-29	2	1
5	2026-06-11	6	5
6	2026-06-12	6	5
7	2026-06-11	7	6
8	2026-06-12	7	6
9	2026-06-17	7	6
\.


--
-- Data for Name: Notas; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Notas" ("Id", "Unidade", "Valor", "AlunoId", "DisciplinaId", "TurmaId", "AnoLetivoId") FROM stdin;
1	1	7.5	2	1	2	1
2	2	8.0	2	1	2	1
3	3	6.0	2	1	2	1
4	1	4.0	2	2	2	1
5	2	5.0	2	2	2	1
6	3	5.5	2	2	2	1
7	4	9.0	2	1	2	1
9	2	8	2	3	2	1
10	5	6.5	2	3	2	1
8	1	8	2	3	2	1
\.


--
-- Data for Name: RelatosAula; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."RelatosAula" ("Id", "Descricao", "DiaLetivoId", "TurmaId", "ProfessorId") FROM stdin;
1	Hoje dei aula de linguagens e eles leram um livro.	1	7	5
2	Hoje eles estudaram operações matemáticas básicas.	3	7	5
3	Aula sobre adição e subtração com material dourado. Turma participativa, todos concluíram os exercícios propostos.	14	2	1
\.


--
-- Data for Name: TurmaDisciplinaProfessores; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."TurmaDisciplinaProfessores" ("Id", "TurmaId", "DisciplinaId", "ProfessorId", "AnoLetivoId") FROM stdin;
1	2	1	2	1
2	2	2	2	1
3	3	1	2	1
4	4	3	5	2
8	5	2	5	1
12	7	2	5	6
13	7	1	5	6
16	8	5	5	5
17	6	6	5	5
\.


--
-- Data for Name: Turmas; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Turmas" ("Id", "Nome", "Segmento", "Ativo", "AnoLetivoId") FROM stdin;
2	1o Ano A	Fundamental	t	1
3	2o Ano B	Fundamental	t	1
4	Turma A Maternal	Maternal	t	2
5	Maternal 1 A	Maternal	t	1
6	Maternal 2 A	Maternal	t	5
7	Infantil 1	Maternal	t	6
8	4º ano A	Fundamental	t	5
\.


--
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."Users" ("Id", "Nome", "Email", "PasswordHash", "Role", "Ativo") FROM stdin;
5	Ângela Maria Lima Pereira	angela@escola.com	$2a$11$pBG7o/2JQUI687xc0y9A8ePNGmJ2ZkbwqVDm7gOD3qAhz5vGDspty	Professor	t
6	Luquinhas	lucas@escola.com	$2a$11$pENJ2dzxWRPrZH5LWcuD3uFHF.Ui7/ovrGGfiV8UPPs0GZN041IoC	Aluno	t
7	Diretor	diretor@escola.com	$2a$11$oIxqBq6e3duxjsKXBaexUOqw/VhEv.qZv9Nx22jR9.VAomTzh/JSW	Diretor	t
4	Pedro Lima	pedro@escola.com	$2a$11$oIxqBq6e3duxjsKXBaexUOqw/VhEv.qZv9Nx22jR9.VAomTzh/JSW	Aluno	t
2	Prof. João	joao@escola.com	$2a$11$oIxqBq6e3duxjsKXBaexUOqw/VhEv.qZv9Nx22jR9.VAomTzh/JSW	Professor	t
3	Maria Souza	maria@escola.com	$2a$11$oIxqBq6e3duxjsKXBaexUOqw/VhEv.qZv9Nx22jR9.VAomTzh/JSW	Aluno	t
1	Administrador	admin@escola.com	$2a$11$oIxqBq6e3duxjsKXBaexUOqw/VhEv.qZv9Nx22jR9.VAomTzh/JSW	Admin	t
\.


--
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: admin_escola_db
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260423120051_InitialCreate	8.0.0
20260427123826_FixDataNascimentoDateOnly	8.0.0
20260611110230_CascadeDeleteTurma_FixAlunoUserId	8.0.0
20260611112057_FixAlunoUniqueIndexPartial	8.0.0
20260615192828_AddDiaLetivoRelatoAula	8.0.0
20260617124039_AddObservacaoFrequenciaAluno	8.0.0
20260617133725_AddSegmentoToDisciplina	8.0.0
20260801142122_AddSegmentoToDiaLetivo	8.0.0
\.


--
-- Name: Alunos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Alunos_Id_seq"', 17, true);


--
-- Name: AnosLetivos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."AnosLetivos_Id_seq"', 6, true);


--
-- Name: DesenvolvimentosMaternal_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."DesenvolvimentosMaternal_Id_seq"', 14, true);


--
-- Name: DiasLetivos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."DiasLetivos_Id_seq"', 14, true);


--
-- Name: Disciplinas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Disciplinas_Id_seq"', 6, true);


--
-- Name: FrequenciaAlunos_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."FrequenciaAlunos_Id_seq"', 9, true);


--
-- Name: Frequencias_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Frequencias_Id_seq"', 9, true);


--
-- Name: Notas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Notas_Id_seq"', 10, true);


--
-- Name: RelatosAula_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."RelatosAula_Id_seq"', 3, true);


--
-- Name: TurmaDisciplinaProfessores_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."TurmaDisciplinaProfessores_Id_seq"', 17, true);


--
-- Name: Turmas_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Turmas_Id_seq"', 8, true);


--
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin_escola_db
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 7, true);


--
-- Name: Alunos PK_Alunos; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Alunos"
    ADD CONSTRAINT "PK_Alunos" PRIMARY KEY ("Id");


--
-- Name: AnosLetivos PK_AnosLetivos; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."AnosLetivos"
    ADD CONSTRAINT "PK_AnosLetivos" PRIMARY KEY ("Id");


--
-- Name: DesenvolvimentosMaternal PK_DesenvolvimentosMaternal; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DesenvolvimentosMaternal"
    ADD CONSTRAINT "PK_DesenvolvimentosMaternal" PRIMARY KEY ("Id");


--
-- Name: DiasLetivos PK_DiasLetivos; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DiasLetivos"
    ADD CONSTRAINT "PK_DiasLetivos" PRIMARY KEY ("Id");


--
-- Name: Disciplinas PK_Disciplinas; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Disciplinas"
    ADD CONSTRAINT "PK_Disciplinas" PRIMARY KEY ("Id");


--
-- Name: FrequenciaAlunos PK_FrequenciaAlunos; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."FrequenciaAlunos"
    ADD CONSTRAINT "PK_FrequenciaAlunos" PRIMARY KEY ("Id");


--
-- Name: Frequencias PK_Frequencias; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Frequencias"
    ADD CONSTRAINT "PK_Frequencias" PRIMARY KEY ("Id");


--
-- Name: Notas PK_Notas; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Notas"
    ADD CONSTRAINT "PK_Notas" PRIMARY KEY ("Id");


--
-- Name: RelatosAula PK_RelatosAula; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."RelatosAula"
    ADD CONSTRAINT "PK_RelatosAula" PRIMARY KEY ("Id");


--
-- Name: TurmaDisciplinaProfessores PK_TurmaDisciplinaProfessores; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."TurmaDisciplinaProfessores"
    ADD CONSTRAINT "PK_TurmaDisciplinaProfessores" PRIMARY KEY ("Id");


--
-- Name: Turmas PK_Turmas; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Turmas"
    ADD CONSTRAINT "PK_Turmas" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: IX_Alunos_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Alunos_AnoLetivoId" ON public."Alunos" USING btree ("AnoLetivoId");


--
-- Name: IX_Alunos_TurmaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Alunos_TurmaId" ON public."Alunos" USING btree ("TurmaId");


--
-- Name: IX_Alunos_UserId_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_Alunos_UserId_AnoLetivoId" ON public."Alunos" USING btree ("UserId", "AnoLetivoId") WHERE ("Ativo" = true);


--
-- Name: IX_DesenvolvimentosMaternal_AlunoId_Bimestre_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_DesenvolvimentosMaternal_AlunoId_Bimestre_AnoLetivoId" ON public."DesenvolvimentosMaternal" USING btree ("AlunoId", "Bimestre", "AnoLetivoId");


--
-- Name: IX_DesenvolvimentosMaternal_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_DesenvolvimentosMaternal_AnoLetivoId" ON public."DesenvolvimentosMaternal" USING btree ("AnoLetivoId");


--
-- Name: IX_DesenvolvimentosMaternal_TurmaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_DesenvolvimentosMaternal_TurmaId" ON public."DesenvolvimentosMaternal" USING btree ("TurmaId");


--
-- Name: IX_DiasLetivos_AnoLetivoId_Data_Segmento; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_DiasLetivos_AnoLetivoId_Data_Segmento" ON public."DiasLetivos" USING btree ("AnoLetivoId", "Data", "Segmento");


--
-- Name: IX_FrequenciaAlunos_AlunoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_FrequenciaAlunos_AlunoId" ON public."FrequenciaAlunos" USING btree ("AlunoId");


--
-- Name: IX_FrequenciaAlunos_FrequenciaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_FrequenciaAlunos_FrequenciaId" ON public."FrequenciaAlunos" USING btree ("FrequenciaId");


--
-- Name: IX_Frequencias_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Frequencias_AnoLetivoId" ON public."Frequencias" USING btree ("AnoLetivoId");


--
-- Name: IX_Frequencias_TurmaId_Data; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_Frequencias_TurmaId_Data" ON public."Frequencias" USING btree ("TurmaId", "Data");


--
-- Name: IX_Notas_AlunoId_DisciplinaId_Unidade_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_Notas_AlunoId_DisciplinaId_Unidade_AnoLetivoId" ON public."Notas" USING btree ("AlunoId", "DisciplinaId", "Unidade", "AnoLetivoId");


--
-- Name: IX_Notas_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Notas_AnoLetivoId" ON public."Notas" USING btree ("AnoLetivoId");


--
-- Name: IX_Notas_DisciplinaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Notas_DisciplinaId" ON public."Notas" USING btree ("DisciplinaId");


--
-- Name: IX_Notas_TurmaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Notas_TurmaId" ON public."Notas" USING btree ("TurmaId");


--
-- Name: IX_RelatosAula_DiaLetivoId_TurmaId_ProfessorId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_RelatosAula_DiaLetivoId_TurmaId_ProfessorId" ON public."RelatosAula" USING btree ("DiaLetivoId", "TurmaId", "ProfessorId");


--
-- Name: IX_RelatosAula_ProfessorId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_RelatosAula_ProfessorId" ON public."RelatosAula" USING btree ("ProfessorId");


--
-- Name: IX_RelatosAula_TurmaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_RelatosAula_TurmaId" ON public."RelatosAula" USING btree ("TurmaId");


--
-- Name: IX_TurmaDisciplinaProfessores_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_TurmaDisciplinaProfessores_AnoLetivoId" ON public."TurmaDisciplinaProfessores" USING btree ("AnoLetivoId");


--
-- Name: IX_TurmaDisciplinaProfessores_DisciplinaId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_TurmaDisciplinaProfessores_DisciplinaId" ON public."TurmaDisciplinaProfessores" USING btree ("DisciplinaId");


--
-- Name: IX_TurmaDisciplinaProfessores_ProfessorId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_TurmaDisciplinaProfessores_ProfessorId" ON public."TurmaDisciplinaProfessores" USING btree ("ProfessorId");


--
-- Name: IX_TurmaDisciplinaProfessores_TurmaId_DisciplinaId_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE UNIQUE INDEX "IX_TurmaDisciplinaProfessores_TurmaId_DisciplinaId_AnoLetivoId" ON public."TurmaDisciplinaProfessores" USING btree ("TurmaId", "DisciplinaId", "AnoLetivoId");


--
-- Name: IX_Turmas_AnoLetivoId; Type: INDEX; Schema: public; Owner: admin_escola_db
--

CREATE INDEX "IX_Turmas_AnoLetivoId" ON public."Turmas" USING btree ("AnoLetivoId");


--
-- Name: Alunos FK_Alunos_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Alunos"
    ADD CONSTRAINT "FK_Alunos_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: Alunos FK_Alunos_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Alunos"
    ADD CONSTRAINT "FK_Alunos_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: Alunos FK_Alunos_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Alunos"
    ADD CONSTRAINT "FK_Alunos_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: DesenvolvimentosMaternal FK_DesenvolvimentosMaternal_Alunos_AlunoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DesenvolvimentosMaternal"
    ADD CONSTRAINT "FK_DesenvolvimentosMaternal_Alunos_AlunoId" FOREIGN KEY ("AlunoId") REFERENCES public."Alunos"("Id") ON DELETE CASCADE;


--
-- Name: DesenvolvimentosMaternal FK_DesenvolvimentosMaternal_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DesenvolvimentosMaternal"
    ADD CONSTRAINT "FK_DesenvolvimentosMaternal_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: DesenvolvimentosMaternal FK_DesenvolvimentosMaternal_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DesenvolvimentosMaternal"
    ADD CONSTRAINT "FK_DesenvolvimentosMaternal_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: DiasLetivos FK_DiasLetivos_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."DiasLetivos"
    ADD CONSTRAINT "FK_DiasLetivos_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: FrequenciaAlunos FK_FrequenciaAlunos_Alunos_AlunoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."FrequenciaAlunos"
    ADD CONSTRAINT "FK_FrequenciaAlunos_Alunos_AlunoId" FOREIGN KEY ("AlunoId") REFERENCES public."Alunos"("Id") ON DELETE CASCADE;


--
-- Name: FrequenciaAlunos FK_FrequenciaAlunos_Frequencias_FrequenciaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."FrequenciaAlunos"
    ADD CONSTRAINT "FK_FrequenciaAlunos_Frequencias_FrequenciaId" FOREIGN KEY ("FrequenciaId") REFERENCES public."Frequencias"("Id") ON DELETE CASCADE;


--
-- Name: Frequencias FK_Frequencias_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Frequencias"
    ADD CONSTRAINT "FK_Frequencias_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: Frequencias FK_Frequencias_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Frequencias"
    ADD CONSTRAINT "FK_Frequencias_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: Notas FK_Notas_Alunos_AlunoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Notas"
    ADD CONSTRAINT "FK_Notas_Alunos_AlunoId" FOREIGN KEY ("AlunoId") REFERENCES public."Alunos"("Id") ON DELETE CASCADE;


--
-- Name: Notas FK_Notas_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Notas"
    ADD CONSTRAINT "FK_Notas_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: Notas FK_Notas_Disciplinas_DisciplinaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Notas"
    ADD CONSTRAINT "FK_Notas_Disciplinas_DisciplinaId" FOREIGN KEY ("DisciplinaId") REFERENCES public."Disciplinas"("Id") ON DELETE CASCADE;


--
-- Name: Notas FK_Notas_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Notas"
    ADD CONSTRAINT "FK_Notas_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: RelatosAula FK_RelatosAula_DiasLetivos_DiaLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."RelatosAula"
    ADD CONSTRAINT "FK_RelatosAula_DiasLetivos_DiaLetivoId" FOREIGN KEY ("DiaLetivoId") REFERENCES public."DiasLetivos"("Id") ON DELETE CASCADE;


--
-- Name: RelatosAula FK_RelatosAula_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."RelatosAula"
    ADD CONSTRAINT "FK_RelatosAula_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: RelatosAula FK_RelatosAula_Users_ProfessorId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."RelatosAula"
    ADD CONSTRAINT "FK_RelatosAula_Users_ProfessorId" FOREIGN KEY ("ProfessorId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: TurmaDisciplinaProfessores FK_TurmaDisciplinaProfessores_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."TurmaDisciplinaProfessores"
    ADD CONSTRAINT "FK_TurmaDisciplinaProfessores_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- Name: TurmaDisciplinaProfessores FK_TurmaDisciplinaProfessores_Disciplinas_DisciplinaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."TurmaDisciplinaProfessores"
    ADD CONSTRAINT "FK_TurmaDisciplinaProfessores_Disciplinas_DisciplinaId" FOREIGN KEY ("DisciplinaId") REFERENCES public."Disciplinas"("Id") ON DELETE CASCADE;


--
-- Name: TurmaDisciplinaProfessores FK_TurmaDisciplinaProfessores_Turmas_TurmaId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."TurmaDisciplinaProfessores"
    ADD CONSTRAINT "FK_TurmaDisciplinaProfessores_Turmas_TurmaId" FOREIGN KEY ("TurmaId") REFERENCES public."Turmas"("Id") ON DELETE CASCADE;


--
-- Name: TurmaDisciplinaProfessores FK_TurmaDisciplinaProfessores_Users_ProfessorId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."TurmaDisciplinaProfessores"
    ADD CONSTRAINT "FK_TurmaDisciplinaProfessores_Users_ProfessorId" FOREIGN KEY ("ProfessorId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


--
-- Name: Turmas FK_Turmas_AnosLetivos_AnoLetivoId; Type: FK CONSTRAINT; Schema: public; Owner: admin_escola_db
--

ALTER TABLE ONLY public."Turmas"
    ADD CONSTRAINT "FK_Turmas_AnosLetivos_AnoLetivoId" FOREIGN KEY ("AnoLetivoId") REFERENCES public."AnosLetivos"("Id") ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict cuQanobPXERIwTwzrNhEhB7vhlyViNp6TJ5W0SZU9U89DRaDNanuOM68RkC1Pig

